### ISSUE TITLE
Mark-lines with Label

### ISSUE THREAD

**Issue by attiqeurrehman** [brightec/JMMarkSlider#1]
Hi, 

It's an awesome control you have build. It would be a lot better if we you can incorporate labels for mark line on the bottom of slider. 

Let me know what do you think. 

Thanks,
Attiqe

**Comment by joamafer** [comment]
Hello!

Sure, I'll try to improve as you suggested! Thanks for your feedback :)

**Comment by attiqeurrehman** [comment]
Jose,

You were quick to reply and it's another plus :), thanks for taking it
under advisement.

-A

On Sat, Dec 6, 2014 at 11:55 PM, Jose Antonio notifications@github.com
wrote:

> Hello!
> 
> Sure, I'll try to improve as you suggested! Thanks for your feedback :)
> 
> El sábado, 6 de diciembre de 2014, attiqeurrehman <
> notifications@github.com>
> escribió:
> 
> > Hi,
> > 
> > It's an awesome control you have build. It would be a lot better if we
> > you
> > can incorporate labels for mark line on the bottom of slider.
> > 
> > Let me know what do you think.
> > 
> > Thanks,
> > Attiqe
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/brightec/JMMarkSlider/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brightec/JMMarkSlider/issues/1#issuecomment-65909348.

## 

Attiqe Ur Rehman
